export const ticketFormTemplateController = async (req, res) => {
  try {
    res.json({
      "Timestamp": 0,
      "Obj": {
        "data": {
          "InfoElevio": "",
          "Id": "",
          "ProductLineACPGuid": "",
          "ProductACPGuid": "",
          "AreaACPGuid": "",
          "ModuleACPGuid": "",
          "ProgramCode": "",
          "ReleaseCode": 0,
          "Build": "",
          "OperatingSystemCode": 0,
          "ContactReasonCode": 0,
          "PriorityCode": 0,
          "Subject": "",
          "ContactName": "",
          "Email": "",
          "FavoriteTelephone": "",
          "Telephone": "",
          "RecallHourFrom": null,
          "RecallHourTo": null,
          "RecallDate": "2025-01-16T09:52:46.5192157+01:00",
          "AvailabilityHourTo": null,
          "AvailabilityHourFrom": null,
          "Description": "",
          "Communications": "",
          "AttachmentId": "",
          "InternalNote": "",
          "TicketTypeCode": 1
        },
        "settings": {
          "fields": [
            {
              "id": 131,
              "field": "InfoElevio",
              "label": "Info Elevio",
              "labelContId": 18939,
              "labelShortContId": null,
              "labelShort": "Info Elevio",
              "description": null,
              "descriptionContId": null,
              "order": 2,
              "type": "Text",
              "widget": "TextArea",
              "regex": null,
              "editable": true,
              "colspan": 1,
              "required": false,
              "url": "",
              "visible": true,
              "isBaseField": false,
              "extKey": "InfoElevio",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 2,
              "isQuickAction": false,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 25,
              "field": "Id",
              "label": "Id",
              "labelContId": 2191,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 4,
              "type": "String",
              "widget": "TextBox",
              "regex": null,
              "editable": false,
              "colspan": 12,
              "required": false,
              "url": null,
              "visible": false,
              "isBaseField": true,
              "extKey": "Id",
              "isMandatory": true,
              "isCustomerField": true,
              "tabId": 1,
              "isQuickAction": false,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 4,
              "field": "ProductLineACPGuid",
              "label": "Linea Prodotto",
              "labelContId": 2172,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 6,
              "type": "String",
              "widget": "DropDown",
              "regex": null,
              "editable": true,
              "colspan": 6,
              "required": true,
              "url": "/v1/Quadruple/ProductLine",
              "visible": true,
              "isBaseField": true,
              "extKey": "ProductLineACPGuid",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 1,
              "isQuickAction": true,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 3,
              "field": "ProductACPGuid",
              "label": "Procedura",
              "labelContId": 2171,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 10,
              "type": "String",
              "widget": "DropDown",
              "regex": null,
              "editable": true,
              "colspan": 6,
              "required": true,
              "url": "/v1/Quadruple/Procedure/${ProductLineACPGuid}",
              "visible": true,
              "isBaseField": true,
              "extKey": "ProductACPGuid",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 1,
              "isQuickAction": true,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 5,
              "field": "AreaACPGuid",
              "label": "Area",
              "labelContId": 2173,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 11,
              "type": "String",
              "widget": "DropDown",
              "regex": null,
              "editable": true,
              "colspan": 6,
              "required": true,
              "url": "/v1/Quadruple/Area/${ProductACPGuid}",
              "visible": true,
              "isBaseField": true,
              "extKey": "AreaACPGuid",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 1,
              "isQuickAction": true,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 6,
              "field": "ModuleACPGuid",
              "label": "Modulo",
              "labelContId": 2174,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 12,
              "type": "String",
              "widget": "DropDown",
              "regex": null,
              "editable": true,
              "colspan": 6,
              "required": true,
              "url": "/v1/Quadruple/Module/${AreaACPGuid}",
              "visible": true,
              "isBaseField": true,
              "extKey": "ModuleACPGuid",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 1,
              "isQuickAction": true,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 7,
              "field": "ProgramCode",
              "label": "Programma",
              "labelContId": 2175,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 13,
              "type": "String",
              "widget": "DropDown",
              "regex": null,
              "editable": true,
              "colspan": 6,
              "required": false,
              "url": "/v1/Program/Module/${ModuleACPGuid}",
              "visible": true,
              "isBaseField": true,
              "extKey": "ProgramCode",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 1,
              "isQuickAction": true,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 8,
              "field": "ReleaseCode",
              "label": "Release",
              "labelContId": 2176,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 14,
              "type": "Number",
              "widget": "DropDown",
              "regex": null,
              "editable": true,
              "colspan": 6,
              "required": false,
              "url": "/v1/Procedure/Module/${ModuleACPGuid}/Release",
              "visible": true,
              "isBaseField": true,
              "extKey": "ReleaseCode",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 1,
              "isQuickAction": true,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 9,
              "field": "Build",
              "label": "Build",
              "labelContId": 2177,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 15,
              "type": "String",
              "widget": "TextBox",
              "regex": null,
              "editable": true,
              "colspan": 6,
              "required": false,
              "url": null,
              "visible": true,
              "isBaseField": true,
              "extKey": "Build",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 1,
              "isQuickAction": true,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 10,
              "field": "OperatingSystemCode",
              "label": "Sistema Operativo",
              "labelContId": 2178,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 16,
              "type": "Number",
              "widget": "DropDown",
              "regex": null,
              "editable": true,
              "colspan": 6,
              "required": false,
              "url": "/v1/OperatingSystem",
              "visible": true,
              "isBaseField": true,
              "extKey": "OperatingSystemCode",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 2,
              "isQuickAction": false,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 11,
              "field": "ContactReasonCode",
              "label": "Motivo di contatto",
              "labelContId": 2179,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 17,
              "type": "Number",
              "widget": "DropDown",
              "regex": null,
              "editable": true,
              "colspan": 6,
              "required": true,
              "url": "/v1/ContactReason",
              "visible": true,
              "isBaseField": true,
              "extKey": "ContactReasonCode",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 2,
              "isQuickAction": false,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 12,
              "field": "PriorityCode",
              "label": "Priorità",
              "labelContId": 2180,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 18,
              "type": "Number",
              "widget": "DropDown",
              "regex": null,
              "editable": true,
              "colspan": 6,
              "required": true,
              "url": "/v1/Priority",
              "visible": true,
              "isBaseField": true,
              "extKey": "PriorityCode",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 1,
              "isQuickAction": false,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 13,
              "field": "Subject",
              "label": "Oggetto",
              "labelContId": 2181,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 19,
              "type": "String",
              "widget": "TextBox",
              "regex": null,
              "editable": true,
              "colspan": 6,
              "required": true,
              "url": null,
              "visible": true,
              "isBaseField": true,
              "extKey": "Subject",
              "isMandatory": true,
              "isCustomerField": true,
              "tabId": 1,
              "isQuickAction": false,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 14,
              "field": "ContactName",
              "label": "Nominativo da contattare",
              "labelContId": 2182,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 20,
              "type": "String",
              "widget": "TextBox",
              "regex": null,
              "editable": true,
              "colspan": 6,
              "required": true,
              "url": null,
              "visible": true,
              "isBaseField": true,
              "extKey": "ContactName",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 3,
              "isQuickAction": false,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 15,
              "field": "Email",
              "label": "Email",
              "labelContId": 2183,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 21,
              "type": "String",
              "widget": "TextBox",
              "regex": "^(([^<>()\\[\\]\\\\.,;:\\s@\"]+(\\.[^<>()\\[\\]\\\\.,;:\\s@\"]+)*)|(\".+\"))@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$",
              "editable": true,
              "colspan": 6,
              "required": true,
              "url": null,
              "visible": true,
              "isBaseField": true,
              "extKey": "Email",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 3,
              "isQuickAction": false,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 18,
              "field": "FavoriteTelephone",
              "label": "Telefono Preferito",
              "labelContId": 2186,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 22,
              "type": "String",
              "widget": "TextBox",
              "regex": "\\+?\\d+",
              "editable": true,
              "colspan": 6,
              "required": true,
              "url": null,
              "visible": true,
              "isBaseField": true,
              "extKey": "FavoriteTelephone",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 3,
              "isQuickAction": false,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 16,
              "field": "Telephone",
              "label": "Altro Recapito Telefonico",
              "labelContId": 2184,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 23,
              "type": "String",
              "widget": "TextBox",
              "regex": "\\+?\\d+",
              "editable": true,
              "colspan": 6,
              "required": false,
              "url": null,
              "visible": true,
              "isBaseField": true,
              "extKey": "Telephone",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 3,
              "isQuickAction": false,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 19,
              "field": "RecallHourFrom",
              "label": "Fascia Oraria Richiama dalle",
              "labelContId": 2187,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 24,
              "type": "Time",
              "widget": "TimePicker",
              "regex": null,
              "editable": true,
              "colspan": 6,
              "required": false,
              "url": null,
              "visible": true,
              "isBaseField": true,
              "extKey": "RecallHourFrom",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 1,
              "isQuickAction": false,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 24,
              "field": "RecallHourTo",
              "label": "Fascia Oraria Richiama fino le",
              "labelContId": 2190,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 25,
              "type": "Time",
              "widget": "TimePicker",
              "regex": null,
              "editable": true,
              "colspan": 6,
              "required": false,
              "url": null,
              "visible": true,
              "isBaseField": true,
              "extKey": "RecallHourTo",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 1,
              "isQuickAction": false,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 35,
              "field": "RecallDate",
              "label": "Data Richiamare",
              "labelContId": 2201,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 26,
              "type": "DateTime",
              "widget": "DatePicker",
              "regex": null,
              "editable": true,
              "colspan": 12,
              "required": false,
              "url": null,
              "visible": true,
              "isBaseField": true,
              "extKey": "RecallDate",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 0,
              "isQuickAction": false,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 30,
              "field": "AvailabilityHourTo",
              "label": "Fascia Oraria di reperibilità fino le",
              "labelContId": 2196,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 27,
              "type": "Time",
              "widget": "TimePicker",
              "regex": null,
              "editable": true,
              "colspan": 6,
              "required": false,
              "url": null,
              "visible": true,
              "isBaseField": true,
              "extKey": "AvailabilityHourTo",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 1,
              "isQuickAction": false,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 31,
              "field": "AvailabilityHourFrom",
              "label": "Fascia Oraria di reperibilità dalle",
              "labelContId": 2197,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 28,
              "type": "Time",
              "widget": "TimePicker",
              "regex": null,
              "editable": true,
              "colspan": 6,
              "required": false,
              "url": null,
              "visible": true,
              "isBaseField": true,
              "extKey": "AvailabilityHourFrom",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 1,
              "isQuickAction": false,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 1,
              "field": "Description",
              "label": "Testo Quesito",
              "labelContId": 2170,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 29,
              "type": "String",
              "widget": "TextArea",
              "regex": null,
              "editable": true,
              "colspan": 12,
              "required": true,
              "url": null,
              "visible": true,
              "isBaseField": true,
              "extKey": "Description",
              "isMandatory": true,
              "isCustomerField": true,
              "tabId": 1,
              "isQuickAction": false,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            {
              "id": 27,
              "field": "Communications",
              "label": "Comunicazioni",
              "labelContId": 2193,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 30,
              "type": "String",
              "widget": "TextArea",
              "regex": null,
              "editable": true,
              "colspan": 12,
              "required": false,
              "url": null,
              "visible": true,
              "isBaseField": true,
              "extKey": "Communications",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 2,
              "isQuickAction": false,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            },
            // {
            //   "id": 17,
            //   "field": "AttachmentId",
            //   "label": "Allegato",
            //   "labelContId": 2185,
            //   "labelShortContId": null,
            //   "labelShort": "",
            //   "description": null,
            //   "descriptionContId": null,
            //   "order": 31,
            //   "type": "FileId",
            //   "widget": "Attachment",
            //   "regex": null,
            //   "editable": true,
            //   "colspan": 12,
            //   "required": false,
            //   "url": "api/v1/TicketAttachment",
            //   "visible": true,
            //   "isBaseField": true,
            //   "extKey": "AttachmentId",
            //   "isMandatory": false,
            //   "isCustomerField": true,
            //   "tabId": 2,
            //   "isQuickAction": false,
            //   "options": [],
            //   "connectedEntityId": 0,
            //   "connectedEntityColumnId": 0,
            //   "connectedEntityColumnName": null
            // },
            {
              "id": 29,
              "field": "InternalNote",
              "label": "Note interne old",
              "labelContId": 2195,
              "labelShortContId": null,
              "labelShort": "",
              "description": null,
              "descriptionContId": null,
              "order": 35,
              "type": "String",
              "widget": "TextArea",
              "regex": null,
              "editable": false,
              "colspan": 12,
              "required": false,
              "url": null,
              "visible": true,
              "isBaseField": true,
              "extKey": "InternalNote",
              "isMandatory": false,
              "isCustomerField": true,
              "tabId": 1,
              "isQuickAction": false,
              "options": [],
              "connectedEntityId": 0,
              "connectedEntityColumnId": 0,
              "connectedEntityColumnName": null
            }
          ],
          "tabs": [
            {
              "id": 1,
              "title": "Attributi Ticket",
              "tabOrder": 1,
              "TabTitleContId": 3345
            },
            {
              "id": 2,
              "title": "Parametri Ticket",
              "tabOrder": 2,
              "TabTitleContId": 3346
            },
            {
              "id": 3,
              "title": "Contatti",
              "tabOrder": 3,
              "TabTitleContId": 3347
            }
          ],
          "columnsPerRow": 3
        },
        "ticketID": 0,
        "TicketRowVersion": null
      },
      "ResultType": 2,
      "ResultTypeString": "Info",
      "Messages": [],
      "ErrorFields": []
    });
  } catch (error) {
    console.error('❌ Errore nel recupero del template di creazione ticket:', error);
    res.status(500).json({ message: 'Errore nel recupero del template di creazione ticket' });
  }
};